
# Preparation

To conduct Sentinel Asia activities, there are several things that need to be prepared, (1) Hardware, (2) softwares and (3) Standard Operational Procedures.

## Hardwares
There are three main computers used for Sentinel Asia works, (1) CentOS Linux , (2) Windows PC and (3) MacPro. CentOS Linux is used as Image Management System, activating scripts for PDAN website and serve as data storage downloaded from Sentinel Asia website. Since we will not continue to use PDAN website, CentOS Linux can be develop as the server for crowdsourcing or field validation by implementing DRMSurvey or Ushahidi for example. Windows PC is used to handle processing data related to flood, while MacPro is used to process data related to geological hazard such as volcano and earthquake. 

## Softwares
The main softwares for processing data can be divided to proprietary and open source sofwares. ArcGIS and ENVI are main proprietary sofwares used, while for open source softwares, QGIS, SNAP and GMT5SAR are utilized.

## Standard Operational Procedures

Standard Operational Procedures (SOP) is the main procedure develop for each type of disasters. The main objective of writing this SOP is to standardize the process, so anyone can do the process with the same output or result.


<!-- This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$. -->

<!-- The **bookdown** package can be installed from CRAN or Github: -->

<!-- ```{r eval=FALSE} -->
<!-- install.packages("bookdown") -->
<!-- # or the development version -->
<!-- # devtools::install_github("rstudio/bookdown") -->
<!-- ``` -->

<!-- Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`. -->

<!-- To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>. -->

<!-- ```{r include=FALSE} -->
<!-- # automatically create a bib database for R packages -->
<!-- knitr::write_bib(c( -->
<!--   .packages(), 'bookdown', 'knitr', 'rmarkdown' -->
<!-- ), 'packages.bib') -->
<!-- ``` -->